### ISSUE TITLE
PR to make item-assets part of core

### ISSUE THREAD

**Issue by matthewhanson** [stac-extensions/item-assets#3]
Create a PR to add the item-assets extension to be part of core in a Collection, to be a part of next STAC release.

**Comment by tschaub** [comment]
This would be nice.

We're wanting to use the `eo` and `raster` extensions to provide additional information about assets.  In addition, we'd like to be able to describe the assets for all items in a collection at the top level of a collection.  I imagine this isn't easy to do without new stac, eo, and raster releases, but curious if others have ideas.

**Comment by tschaub** [comment]
@m-mohr - I see that the https://github.com/stac-extensions/item-assets/blob/v1.0.0/examples/example-landsat8.json example uses `eo` properties on assets within `item_assets`.  It doesn't look to me like these would be validated by the [`eo` schema](https://github.com/stac-extensions/eo/blob/main/json-schema/schema.json), but I might be missing something.

We're trying to decide whether to (mis-)use `assets` at the collection level to represent common assets for all items (not valid unless we add a non-empty `href`) or to try to make things work with `item_assets` at the collection level (perhaps awkward with `pystac` or other existing tools if we're also trying to add `eo` and `raster` properties to these assets).

Is there a consensus that `item_assets` should be defined as part of the core spec?

**Comment by m-mohr** [comment]
You can just use the item asset definition extension in STAC 1.0, I don't understand what the blocker is? Can you clarify @tschaub? 

This should validate item_assets in the EO extension: https://github.com/stac-extensions/eo/blob/main/json-schema/schema.json#L94
If it doesn't, then it might be a bug in the schema.

**Comment by tschaub** [comment]
@m-mohr - Thanks.  I had missed that both the [`eo`](https://github.com/stac-extensions/eo/blob/v1.1.0/json-schema/schema.json#L91-L96) and [`raster`](https://github.com/stac-extensions/raster/blob/v1.1.0/json-schema/schema.json#L51-L56) extensions "extend" this extension.

**Comment by emmanuelmathot** [comment]
PR merged in https://github.com/radiantearth/stac-spec/pull/1289.
This extension shall be archived once the STAC version 1.1.0 shall be released.
