### ISSUE TITLE
any or all items?

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/item-assets#4]
The specification says:

> Provide a human-readable definition of assets available in **any** Items belonging to this Collection so that the user can determine the key(s) of assets they are interested in.

Is this meant to be:

> Provide a human-readable definition of assets available in **all** Items belonging to this Collection so that the user can determine the key(s) of assets they are interested in.

Let's say I have a collection where 50% of the items have assets A, B and C and the other 50% only have A and B, what do I report in item_assets?

1. A, B and C (that's why **any** implies to me)
2. A and B (that's what **all** would imply to me).

**Comment by DahnJ** [comment]
Good point, an important clarification to have. I implicitly understood it as the **any** (option 1), but agree it's not explicit in the readme.

If it's indeed option 1, perhaps this warrants an additional field that indicates whether all items have the asset. Something like `always_present: true`. That way we get information covering both options 1 and option 2.

**Comment by emmanuelmathot** [comment]
If we follow the logic of the `summaries`, I would say it is option 1.

**Comment by m-mohr** [comment]
Any thoughts @matthewhanson @gadomski @bitner?

**Comment by bitner** [comment]
I've assumed "any" aka option 1.

**Comment by m-mohr** [comment]
Clarified in https://github.com/stac-extensions/item-assets/commit/279cf840b0b995c8a40e7ea7573137ff5af8f572

I meant to create a PR, but accidentally directly committed via the GitHub Web UI, sorry. If any proposals for improvements should be made, please let me know.
